name: Run Cypress E2E Tests

on:
  push:
    branches:
      - main
      - staging
  pull_request:
    branches:
      - main
      - staging
  deployment_status:

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    # Run tests only for successful deployments or push/pull_request to main/staging
    if: |
      github.event_name != 'deployment_status' || 
      (github.event.deployment_status.state == 'success' && 
       (github.event.deployment_status.deployment.ref == 'refs/heads/main' || 
        github.event.deployment_status.deployment.ref == 'refs/heads/staging'))
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Matches Next.js 15.3.3

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress E2E tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          config-file: cypress.config.ts
          spec: cypress/e2e/**/*.cy.{js,jsx,ts,tsx}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_BASE_URL: ${{ github.event_name == 'deployment_status' && github.event.deployment_status.target_url || (github.ref == 'refs/heads/staging' && 'https://streamlinecorp-web-git-staging-cranner-sfurns-projects.vercel.app' || 'https://streamlinecorp-web.vercel.app') }}
          NEXT_PUBLIC_API_URL: ${{ github.ref == 'refs/heads/staging' && secrets.STAGING_API_URL || secrets.PRODUCTION_API_URL }}
