name: E2E Test on PR

on:
  pull_request:
    branches:
      - "**"

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write

    env:
      BETTER_AUTH_URL: ${{ secrets.BETTER_AUTH_URL }}
      BETTER_AUTH_SECRET: ${{ secrets.BETTER_AUTH_SECRET }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - name: Comment on PR - E2E tests starting
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            🚦 E2E tests are starting for this PR...

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache npm and Next.js build cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build

      - name: Run E2E tests
        run: npx cypress run --reporter json --reporter-options "output=results.json"

      - name: Generate E2E test summary
        run: |
          mkdir -p scripts
          node scripts/parse-cypress-results.js

      - name: Comment on PR - E2E test results
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-path: results.md
