name: E2E Tests

on:
  push:
    branches:
      - staging

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Start Next.js app
        run: npm run build && npm start &
        env:
          NODE_ENV: production

      - name: Wait for site to be ready
        uses: jakejarvis/wait-for-netlify-action@v1
        with:
          url: "http://localhost:3000"
          timeout: 60

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          wait-on: "http://localhost:3000"
          wait-on-timeout: 60
